# Generated by Django 5.1.3 on 2024-11-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id_mobiliario', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
                ('costo', models.CharField(max_length=100)),
                ('fecha_compra', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('id_sucursales', models.CharField(max_length=6)),
            ],
        ),
    ]
