# Generated by Django 5.1.3 on 2024-11-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=10)),
                ('codigo_postal', models.CharField(max_length=6)),
            ],
        ),
    ]
