# Generated by Django 5.1.3 on 2024-11-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_cita', models.CharField(max_length=100)),
                ('monto', models.CharField(max_length=100)),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.DateField()),
                ('estado_pago', models.CharField(max_length=10)),
                ('id_cliente', models.CharField(max_length=6)),
            ],
        ),
    ]
